;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================


[colors]
bg = #0b1220
fg = #cbd5f5
blue = #4f7cff
red = #ff4d5a
white = #ffffff
black = #000000
muted = #6b7280
border = #1e293b
transparent = #00000000
[var]
bar_height = 38

##################
#       BAR      #
##################

################################################################################

# Left Bar
[bar/left]
width = 15%
height = ${var.bar_height}
radius = 10
offset-x = 10
offset-y = 10
background = ${colors.bg}
foreground = ${colors.fg}
border-size = 3
border-color = ${colors.blue}
override-redirect = false
wm-restack = bspwm
enable-ipc = true

font-0 = "JetBrainsMono Nerd Font:size=12;2"
font-2 = "JetBrainsMono Nerd Font:size=12;12"

modules-center = workspaces

#################################################################################

# Center Bar
[bar/center]
width = 5%
height = ${var.bar_height}
radius = 12
offset-x = 45.5%
offset-y = 10
background = ${colors.bg}
border-size = 3
border-color = ${colors.blue}
override-redirect = false
wm-restack = bspwm
enable-ipc = true

font-0 = "JetBrainsMono Nerd Font:size=13;3"

modules-center = clock

##########################################################################

# Right Bar
[bar/right]
width = 11%
height = ${var.bar_height}
radius = 12
offset-x = 87.5%
offset-y = 10
background = ${colors.bg}
border-size = 3
border-color = ${colors.blue}
override-redirect = false 
wm-restack = bspwm
enable-ipc = true

font-0 = "JetBrainsMono Nerd Font:size=12;2"

modules-center =  cpu sep xkeyboard sep alsa

#####################
#      MODULES      #
#####################

#[module/memory]
#type = internal/memory
#interval = 2
#format = <label>
#format-prefix = " 󰍛 "
#format-padding = 1
#format-foreground = #00ff41
#label = %gb_used%

[module/workspaces]
type = internal/xworkspaces
label-active = %name%
label-active-foreground = ${colors.blue}
label-active-background = ${colors.bg}
label-active-font = 2
label-active-padding = 1

# Not active (has windows)
label-occupied = %name%
label-occupied-foreground = ${colors.muted}
label-occupied-padding = 1

# Not active (no windows)
label-empty = %name%
label-empty-foreground = ${colors.muted}
label-empty-padding = 1

[module/clock]
type = internal/date
interval = 1
date = " %I:%M %p"
date-alt = " %a-%m-%d"
label = %date%
label-foreground = ${colors.fg}
label-background = ${colors.bg}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-layout> <label-indicator>
label-layout-padding = 1
label-layout-foreground = #fff
label-indicator-on = %name%
layout-icon-default = some-icon
layout-icon-0 = ru
layout-icon-1 = us
label-indicator-on-capslock = !
label-indicator-off-capslock =

[module/alsa]
type = internal/alsa
format-volume = <ramp-volume> <label-volume>
format-volume-padding = 1
format-muted = 󰖁
format-muted-padding = 1
label-volume = %percentage%%
ramp-volume-0 = %{F#d35f5e}󰖀 %{F-}
ramp-volume-1 = %{F#d35f5e}󰖀 %{F-}
ramp-volume-2 = %{F#d35f5e}󰖀 %{F-}
ramp-volume-3 = %{F#d35f5e}󰖀 %{F-}
ramp-volume-4 = %{F#d35f5e}󰖀 %{F-}
ramp-volume-5 = %{F#d35f5e}󰕾 %{F-}
ramp-volume-6 = %{F#d35f5e}󰕾 %{F-}
ramp-volume-7 = %{F#d35f5e}󰕾 %{F-}
ramp-volume-8 = %{F#d35f5e}󰕾 %{F-}
ramp-volume-9 = %{F#d35f5e}󰕾 %{F-}
ramp-headphones-0 = 
ramp-headphones-1 = 
format-volume-foreground = ${colors.fg}
format-muted-foreground = #d35f5e

[module/wireless]
type = internal/network
interface = wlp4s0
interval = 3.0
udspeed-minwidth = 0
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected =  %essid%
label-connected-foreground = #eefafafa
label-disconnected = 
label-disconnected-foreground = #66ffffff
click-left = nm-connection-editor

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.fg}
label = %percentage%%

[module/sep]
type = custom/text
content = " | "
content-foreground = ${colors.muted}

[settings]
screenchange-reload = true
pseudo-transparency = true 
